version: '3.4'

services:
  discordbot:
    image: matthewiver/cyber-nerd-discord-bot:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "src/index.js"]
