services:
  mongo:
    container_name: CN-MongoDB
    image: mongo:5.0
    ports:
      - "27017:27017"

  discordbot:
    container_name: CN-DiscordBot
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - CQOTD_ID=${CQOTD_ID}
      - MONGODB_URI=${MONGODB_URI}
    env_file:
      - .env