version: '3.8'

services:
  mongo:
    container_name: CN-MongoDB
    image: mongo:5.0
    ports:
      - "27017:27017"

  discordbot:
    container_name: CN-DiscordBot
    build:
      context: .
    depends_on:
      - mongo
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - CQOTD_ID=${CQOTD_ID}
      - MONGODB_URI=mongodb://mongo:27017/cqotd
