let ciscocommandsquestions = [
    {
      category: "Cisco Commands",
      question: "What command displays the current configuration on a Cisco device?",
      answer: "show running-config",
      hint: "Shows the active configuration.",
      blank: "xxxx xxxxxxxxxx-xxxxxx",
      review: "<https://www.cisco.com/c/en/us/td/docs/ios/12_2/configfun/command/reference/cfn_s2.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command saves the running configuration to the startup configuration?",
      answer: "copy running-config startup-config",
      hint: "Copies the active configuration to the saved configuration.",
      blank: "xxxx xxxxxxxxxx-xxxxxx xxxxxxxxxx-xxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/ios-software-releases-112/41232-config-save.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command is used to enter global configuration mode?",
      answer: "configure terminal",
      hint: "Used to access configuration settings.",
      blank: "xxxxxxxx xxxxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/configuration-guides/202684-configuring-a-router.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command reboots a Cisco switch?",
      answer: "reload",
      hint: "Restarts the device.",
      blank: "xxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/switches/catalyst-2950-series-switches/24083-148.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command shows the status of interfaces?",
      answer: "show ip interface brief",
      hint: "Displays IP address and operational status.",
      blank: "xxxx xx xxxxxxxxx xxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/ios-software-releases-122-mainline/20473-90.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command enables an interface on a Cisco switch?",
      answer: "no shutdown",
      hint: "Reactivates a disabled interface.",
      blank: "xx xxxxxxxxx",
      review: "<https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/interface/configuration/15-mt/ir-15-mt-book/ir_no_shut.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command assigns an IP address to an interface?",
      answer: "ip address [IP] [Subnet]",
      hint: "Used in interface configuration mode.",
      blank: "xx xxxxxxx [xx] [xxxxxx]",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/ip-routing/13762-12.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command configures a hostname for a Cisco device?",
      answer: "hostname [name]",
      hint: "Sets a unique device identifier.",
      blank: "xxxxxxxx [xxxxx]",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/configuration-guides/202684-configuring-a-router.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command displays the MAC address table on a switch?",
      answer: "show mac address-table",
      hint: "Lists MAC addresses and associated interfaces.",
      blank: "xxxx xxx xxxxxxx-xxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/switches/catalyst-2900-xl-series-switches/24033-28.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command disables an interface?",
      answer: "shutdown",
      hint: "Opposite of enabling an interface.",
      blank: "xxxxxxxx",
      review: "<https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/interface/configuration/15-mt/ir-15-mt-book/ir_shut.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command sets a VLAN to an interface?",
      answer: "switchport access vlan [VLAN_ID]",
      hint: "Used in interface configuration mode.",
      blank: "xxxxxxxxxx xxxxxx xxxxx [xxxx_xx]",
      review: "<https://www.cisco.com/c/en/us/support/docs/lan-switching/8021q/21022-132.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command enables SSH access on a Cisco device?",
      answer: "ip ssh version 2",
      hint: "Configures secure shell access.",
      blank: "xx xxx xxxxxxx x",
      review: "<https://www.cisco.com/c/en/us/support/docs/security-vpn/ssh/4145-ssh.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command verifies connectivity to another host?",
      answer: "ping [IP]",
      hint: "ICMP utility.",
      blank: "xxxx [xx]",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/routing-information-protocol-rip/13714-ping-traceroute.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command shows the current VLAN configuration?",
      answer: "show vlan brief",
      hint: "Lists VLANs and interfaces.",
      blank: "xxxx xxxx xxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/lan-switching/vlan-configuration/12014-27.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command resets a Cisco device to factory settings?",
      answer: "write erase",
      hint: "Removes all configurations.",
      blank: "xxxxx xxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/system-management/20065-using-write-erase.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command sets a password for console access?",
      answer: "line console 0",
      hint: "Enter console line configuration mode.",
      blank: "xxxx xxxxxxx x",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/configuration-guides/202684-configuring-a-router.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command shows spanning-tree details?",
      answer: "show spanning-tree",
      hint: "Displays STP information.",
      blank: "xxxx xxxxxxxxxx-xxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/lan-switching/spanning-tree-protocol/5234-5.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command enables port security on an interface?",
      answer: "switchport port-security",
      hint: "Used in interface configuration mode.",
      blank: "xxxxxxxxxx xxxx-xxxxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/lan-switching/port-security/12013-17.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command displays all active routes in the routing table?",
      answer: "show ip route",
      hint: "Lists paths to networks.",
      blank: "xxxx xx xxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/routing-information-protocol-rip/13714-ip-routing-table.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command assigns a description to an interface?",
      answer: "description [text]",
      hint: "Used in interface configuration mode.",
      blank: "xxxxxxxxxxx [xxxx]",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-xml/ios/interface/configuration/15-mt/ir-15-mt-book/ir-int-descr.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command enables dynamic trunking on an interface?",
      answer: "switchport mode dynamic desirable",
      hint: "Configures a port for trunking.",
      blank: "xxxxxxxxxx xxxx xxxxxxx xxxxxxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/lan-switching/trunking/24063-185.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command enables a DHCP server on a Cisco router?",
      answer: "ip dhcp pool [name]",
      hint: "Configures a DHCP pool.",
      blank: "xx xxxx xxxx [xxxx]",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/dynamic-address-allocation-resolution/11014-dhcp.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command displays information about CDP neighbors?",
      answer: "show cdp neighbors",
      hint: "Lists directly connected devices.",
      blank: "xxxx xxx xxxxxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/cdp/9308-cdp.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command enables logging on a Cisco device?",
      answer: "logging on",
      hint: "Turns on log generation.",
      blank: "xxxxxxx xx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/system-message-logging/20078-logging-on.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command disables CDP globally on a Cisco device?",
      answer: "no cdp run",
      hint: "Turns off device discovery.",
      blank: "xx xxx xxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/cdp/10512-cdp.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command shows the status of EtherChannel groups?",
      answer: "show etherchannel summary",
      hint: "Lists port-channel details.",
      blank: "xxxx xxxxxxxxxxxx xxxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/lan-switching/etherchannel/12023-4.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command enables routing on a switch?",
      answer: "ip routing",
      hint: "Allows the switch to forward packets.",
      blank: "xx xxxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/routing-information-protocol-rip/13714-ip-routing.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command sets a static route?",
      answer: "ip route [network] [mask] [next-hop]",
      hint: "Used in global configuration mode.",
      blank: "xx xxxxx [xxxxxxx] [xxxx] [xxxx-xxx]",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/static-routing/118006-config-static-routes.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command disables logging on a Cisco device?",
      answer: "no logging console",
      hint: "Stops logging to console.",
      blank: "xx xxxxxxx xxxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/system-message-logging/20078-logging-console.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command configures a default gateway?",
      answer: "ip default-gateway [IP]",
      hint: "Used in global config mode.",
      blank: "xx xxxxxxx-xxxxxxx [xx]",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/ip-routing/13718-defaultgateway.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command enables an IP route?",
      answer: "ip route [network] [mask] [next-hop]",
      hint: "Sets a static route.",
      blank: "xx xxxxx [xxxxxxx] [xxxx] [xxxx-xxx]",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/static-routing/118006-config-static-routes.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command shows the NAT translation table?",
      answer: "show ip nat translations",
      hint: "Displays NAT mappings.",
      blank: "xxxx xx xxx xxxxxxxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/network-address-translation-nat/10103-cisco-nat.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command enables IPv6 routing?",
      answer: "ipv6 unicast-routing",
      hint: "Turns on IPv6 routing.",
      blank: "xxxxx xxxxxxx-xxxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/ipv6/116108-qanda-ipv6-00.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command displays CPU usage statistics?",
      answer: "show processes cpu",
      hint: "Monitors CPU utilization.",
      blank: "xxxx xxxxxxxxx xxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/cpu-usage/21422-cpuusage.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command enables OSPF routing?",
      answer: "router ospf [process-id]",
      hint: "Starts OSPF process.",
      blank: "xxxxxx xxxx [xxxxxx-xx]",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/open-shortest-path-first-ospf/13684-1.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command sets the clock on a Cisco device?",
      answer: "clock set [time] [date]",
      hint: "Adjusts system time.",
      blank: "xxxxx xxxx [xxxx] [xxxx]",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/ios-software-releases-122-mainline/21683-ntpclockset.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command displays current time and date?",
      answer: "show clock",
      hint: "Shows system time.",
      blank: "xxxx xxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/system-management/20022-clock.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command shows ARP table entries?",
      answer: "show ip arp",
      hint: "Lists IP-to-MAC mappings.",
      blank: "xxxx xx xxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/address-resolution-protocol-arp/118630-technote-arp-00.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command configures a default route?",
      answer: "ip route 0.0.0.0 0.0.0.0 [next-hop]",
      hint: "Used in global config mode.",
      blank: "xx xxxxx x.x.x.x x.x.x.x [xxxx-xxx]",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/ip-routing/11605-default-route.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command lists active Telnet sessions?",
      answer: "show sessions",
      hint: "Displays remote connections.",
      blank: "xxxx xxxxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/system-management/20078-sessions.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command clears all dynamic NAT translations?",
      answer: "clear ip nat translations *",
      hint: "Resets NAT entries.",
      blank: "xxxxx xx xxx xxxxxxxxxxx *",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/network-address-translation-nat/10103-cisco-nat.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command shows all logging messages?",
      answer: "show logging",
      hint: "Displays system logs.",
      blank: "xxxx xxxxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/system-message-logging/20078-logging-console.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command shows startup configuration?",
      answer: "show startup-config",
      hint: "Displays saved configuration.",
      blank: "xxxx xxxxxxx-xxxxxx",
      review: "<https://www.cisco.com/c/en/us/td/docs/ios/12_2/configfun/command/reference/cfn_s2.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command enables debugging for all IP packets?",
      answer: "debug ip packet",
      hint: "Logs packet flow details.",
      blank: "xxxxxx xx xxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/network-management/12790-debug-ip-packet.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command disables debugging globally?",
      answer: "no debug all",
      hint: "Turns off all debugs.",
      blank: "xx xxxxx xxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/debugging/13739-debugging.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command displays CDP packets being sent?",
      answer: "debug cdp packets",
      hint: "Logs CDP packet activity.",
      blank: "xxxxxx xxx xxxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/cdp/10512-cdp.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command clears interface counters?",
      answer: "clear counters",
      hint: "Resets traffic stats.",
      blank: "xxxxx xxxxxxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/ios-xe/20078-clear-counters.html>",
    },
    {
      category: "Cisco Commands",
      question: "What command lists all open ports?",
      answer: "show control-plane",
      hint: "Displays interface stats.",
      blank: "xxxx xxxxxxx-xxxxx",
      review: "<https://www.cisco.com/c/en/us/support/docs/ip/port-configuration/20078-control-plane.html>",
    },
  ];
  
  module.exports = {
    category: "Cisco Commands",
    fetchQuestion: async () => {
      const randomIndex = Math.floor(Math.random() * ciscocommandsquestions.length);
      return ciscocommandsquestions[randomIndex];
    },
    getAllQuestions: async () => {
      return ciscocommandsquestions;
    },
  };
  