let ghidraquestions = [
    {
      category: "Ghidra",
      question: "What is Ghidra primarily used for?",
      answer: "Reverse engineering",
      hint: "Analyzing binary code.",
      blank: "xxxxxx xxxxxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "Who developed Ghidra?",
      answer: "NSA",
      hint: "A U.S. government agency.",
      blank: "xxx",
      review: "https://www.nsa.gov/ghidra/",
    },
    {
      category: "Ghidra",
      question: "What programming language is Ghidra written in?",
      answer: "Java",
      hint: "Runs on a virtual machine.",
      blank: "xxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What file format does Ghidra primarily analyze?",
      answer: "PE",
      hint: "Windows Portable Executable.",
      blank: "xx",
      review: "https://docs.microsoft.com/en-us/windows/win32/debug/pe-format",
    },
    {
      category: "Ghidra",
      question: "What does the decompiler in Ghidra do?",
      answer: "Converts binaries to source code",
      hint: "Translates machine code.",
      blank: "xxxxxxxx xxxxxxxx xx xxxxx xxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What feature in Ghidra allows collaborative analysis?",
      answer: "Version tracking",
      hint: "Tracks changes in shared projects.",
      blank: "xxxxxxx xxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What scripting language is supported in Ghidra?",
      answer: "Python",
      hint: "A popular language for automation.",
      blank: "xxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What is the Ghidra component used for binary patching?",
      answer: "Patch Manager",
      hint: "Edits the binary file.",
      blank: "xxxxx xxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What Ghidra feature helps identify functions in binaries?",
      answer: "Function analysis",
      hint: "Focuses on procedures.",
      blank: "xxxxxxx xxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What plugin in Ghidra aids in malware analysis?",
      answer: "FLIRT",
      hint: "Function identification tool.",
      blank: "xxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What is a Ghidra project file called?",
      answer: "Project archive",
      hint: "Stores analysis data.",
      blank: "xxxxxx xxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What is the main user interface of Ghidra?",
      answer: "Code Browser",
      hint: "Displays disassembled code.",
      blank: "xxxx xxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What file format does Ghidra use for saved workspaces?",
      answer: "GZP",
      hint: "Ghidra Zip Project.",
      blank: "xxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What Ghidra feature allows for custom extensions?",
      answer: "Ghidra Plugins",
      hint: "Enhances functionality.",
      blank: "xxxxxx xxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What is the purpose of the Symbol Table in Ghidra?",
      answer: "Stores identifiers",
      hint: "Tracks variables and functions.",
      blank: "xxxxxx xxxxxxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What is the primary input for Ghidra?",
      answer: "Executable files",
      hint: "Binary formats.",
      blank: "xxxxxxxxxx xxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What operating systems support Ghidra?",
      answer: "Windows, macOS, Linux",
      hint: "Cross-platform compatibility.",
      blank: "xxxxxxx, xxxxx, xxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What feature in Ghidra identifies cross-references?",
      answer: "XREF",
      hint: "Tracks references to symbols.",
      blank: "xxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What does Ghidra use for control flow analysis?",
      answer: "Control Flow Graph",
      hint: "Visualizes program flow.",
      blank: "xxxxxx xxxx xxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What scripting framework does Ghidra use?",
      answer: "Java API",
      hint: "Built on Java.",
      blank: "xxxx xxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What Ghidra feature enables undoing changes?",
      answer: "Transaction rollback",
      hint: "Reverts edits.",
      blank: "xxxxxxxxxx xxxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What type of files can Ghidra decompile?",
      answer: "ELF, PE, Mach-O",
      hint: "Linux, Windows, macOS formats.",
      blank: "xxx, xx, xxxx-x",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What is the primary function of the Function Graph in Ghidra?",
      answer: "Visualize function calls",
      hint: "Tracks function relationships.",
      blank: "xxxxxxxx xxxxxxxx xxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What does the Data Type Manager in Ghidra handle?",
      answer: "User-defined types",
      hint: "Tracks custom data structures.",
      blank: "xxxx-xxxxxxx xxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What is Ghidra’s command-line utility called?",
      answer: "analyzeHeadless",
      hint: "Runs analysis without a GUI.",
      blank: "xxxxxxxxxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What is the Ghidra feature for debugging binary files?",
      answer: "Debugger",
      hint: "Step through code execution.",
      blank: "xxxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What is the function of the Program Tree in Ghidra?",
      answer: "Organize code structure",
      hint: "Displays program segments.",
      blank: "xxxxxxxxx xxxx xxxxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What Ghidra feature finds similarities between binaries?",
      answer: "Binary Diffing",
      hint: "Compares two files.",
      blank: "xxxxxx xxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What feature allows customizing analysis workflows in Ghidra?",
      answer: "Task Scheduler",
      hint: "Manages automated tasks.",
      blank: "xxxx xxxxxxxxx",
      review: "https://ghidra-sre.org/",
    },
    {
      category: "Ghidra",
      question: "What file stores Ghidra project settings?",
      answer: "ghidra.prj",
      hint: "Project configuration file.",
      blank: "xxxxxx.xxx",
      review: "https://ghidra-sre.org/",
    },
  ];
  
  module.exports = {
    category: "Ghidra",
    fetchQuestion: async () => {
      const randomIndex = Math.floor(Math.random() * ghidraquestions.length);
      return ghidraquestions[randomIndex];
    },
    getAllQuestions: async () => {
      return ghidraquestions;
    },
  };
  