let offensiveC2Questions = [
    {
      category: "Offensive C2 Frameworks",
      question: "What C2 framework is commonly used for post-exploitation tasks?",
      answer: "Cobalt Strike",
      hint: "Popular among red teams.",
      blank: "xxxxxx xxxxxx",
      review: "https://www.cobaltstrike.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What framework focuses on PowerShell-based attacks?",
      answer: "Empire",
      hint: "Windows-focused C2.",
      blank: "xxxxxx",
      review: "https://github.com/BC-SECURITY/Empire",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What is the primary use of Metasploit?",
      answer: "Exploit delivery",
      hint: "Delivers payloads.",
      blank: "xxxxxx xxxxxxxx",
      review: "https://www.metasploit.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "Which C2 framework is designed for stealthy operations?",
      answer: "BrutRatel",
      hint: "Known for evading detection.",
      blank: "xxxxxxxxxx",
      review: "https://brutratel.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What Metasploit command launches a handler for reverse shells?",
      answer: "exploit -j",
      hint: "Starts a job.",
      blank: "xxxxxxxx -x",
      review: "https://www.metasploit.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What C2 framework is Python-based and modular?",
      answer: "PoshC2",
      hint: "Uses Python and PowerShell.",
      blank: "xxxxxxxx",
      review: "https://github.com/nettitude/PoshC2",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What framework integrates with EDR bypass techniques?",
      answer: "BrutRatel",
      hint: "Stealth against EDR solutions.",
      blank: "xxxxxxxxxx",
      review: "https://brutratel.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What is Cobalt Strike’s primary agent called?",
      answer: "Beacon",
      hint: "Manages sessions.",
      blank: "xxxxxx",
      review: "https://www.cobaltstrike.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What framework is known for cross-platform capabilities?",
      answer: "Sliver",
      hint: "Written in Go.",
      blank: "xxxxxx",
      review: "https://github.com/BishopFox/sliver",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What framework focuses on web-based phishing campaigns?",
      answer: "Gophish",
      hint: "Simulates phishing attacks.",
      blank: "xxxxxxx",
      review: "https://getgophish.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "Which C2 framework includes a graphical user interface (GUI)?",
      answer: "Cobalt Strike",
      hint: "User-friendly interface.",
      blank: "xxxxxx xxxxxx",
      review: "https://www.cobaltstrike.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What is the default port for Metasploit's handler?",
      answer: "4444",
      hint: "Common for reverse shells.",
      blank: "xxxx",
      review: "https://www.metasploit.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What tool is used to generate obfuscated PowerShell payloads?",
      answer: "ObfuscationKit",
      hint: "Focuses on PowerShell evasion.",
      blank: "xxxxxxxxxxxxxxx",
      review: "https://github.com/EmpireProject/Empire",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What is a key feature of BrutRatel over Cobalt Strike?",
      answer: "EDR evasion",
      hint: "Focuses on stealth.",
      blank: "xxx xxxxxxx",
      review: "https://brutratel.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "Which framework is commonly used for phishing email campaigns?",
      answer: "Gophish",
      hint: "Open-source phishing tool.",
      blank: "xxxxxxx",
      review: "https://getgophish.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What is the primary communication method for Cobalt Strike?",
      answer: "HTTPS",
      hint: "Encrypted web traffic.",
      blank: "xxxxx",
      review: "https://www.cobaltstrike.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What Python-based framework offers custom payload creation?",
      answer: "Merlin",
      hint: "Python C2 framework.",
      blank: "xxxxxx",
      review: "https://github.com/Ne0nd0g/merlin",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What Metasploit command generates a payload?",
      answer: "msfvenom",
      hint: "Combines msfpayload and msfencode.",
      blank: "xxxxxxxx",
      review: "https://www.metasploit.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "Which C2 framework is considered lightweight and Go-based?",
      answer: "Sliver",
      hint: "Cross-platform support.",
      blank: "xxxxxx",
      review: "https://github.com/BishopFox/sliver",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What is the primary benefit of Empire's REST API?",
      answer: "Automation",
      hint: "Integrates with scripts.",
      blank: "xxxxxxxx",
      review: "https://github.com/BC-SECURITY/Empire",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What tool is used to simulate advanced persistent threats (APTs)?",
      answer: "CALDERA",
      hint: "Emulates adversary techniques.",
      blank: "xxxxxxxx",
      review: "https://github.com/mitre/caldera",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "Which framework focuses on email-based payload delivery?",
      answer: "Gophish",
      hint: "Simulates phishing attacks.",
      blank: "xxxxxxx",
      review: "https://getgophish.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What C2 framework is an alternative to Metasploit?",
      answer: "Cobalt Strike",
      hint: "Often used for red teaming.",
      blank: "xxxxxx xxxxxx",
      review: "https://www.cobaltstrike.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What communication protocol is supported by Sliver?",
      answer: "DNS",
      hint: "Often used for covert channels.",
      blank: "xxx",
      review: "https://github.com/BishopFox/sliver",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What is the primary feature of Merlin?",
      answer: "Custom payloads",
      hint: "Python-based framework.",
      blank: "xxxxxx xxxxxxx",
      review: "https://github.com/Ne0nd0g/merlin",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "Which framework is built to bypass antivirus software?",
      answer: "BrutRatel",
      hint: "Focuses on stealth and evasion.",
      blank: "xxxxxxxxxx",
      review: "https://brutratel.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What is the default port for Cobalt Strike?",
      answer: "50050",
      hint: "Used for team servers.",
      blank: "xxxxx",
      review: "https://www.cobaltstrike.com/",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What C2 framework is modular and open-source?",
      answer: "Sliver",
      hint: "Supports cross-platform operations.",
      blank: "xxxxxx",
      review: "https://github.com/BishopFox/sliver",
    },
    {
      category: "Offensive C2 Frameworks",
      question: "What is the role of the team server in Cobalt Strike?",
      answer: "Coordinates agents",
      hint: "Manages Beacons.",
      blank: "xxxxxxxxxx xxxxxxx",
      review: "https://www.cobaltstrike.com/",
    },
  ];
  
  module.exports = {
    category: "Offensive C2 Frameworks",
    fetchQuestion: async () => {
      const randomIndex = Math.floor(Math.random() * offensiveC2Questions.length);
      return offensiveC2Questions[randomIndex];
    },
    getAllQuestions: async () => {
      return offensiveC2Questions;
    },
  };
  