let pythonquestions = [
    {
      category: "Python",
      question: "What is Python primarily used for?",
      answer: "General-purpose programming",
      hint: "Used for web development, data analysis, and more.",
      blank: "xxxxxx-xxxxxxx xxxxxxxxxxx",
      review: "<https://www.python.org/about/>",
    },
    {
      category: "Python",
      question: "What is the syntax to create a list in Python?",
      answer: "[]",
      hint: "Uses square brackets.",
      blank: "[]",
      review: "<https://docs.python.org/3/tutorial/datastructures.html>",
    },
    {
      category: "Python",
      question: "What is the command to install a Python package?",
      answer: "pip install",
      hint: "Python package manager.",
      blank: "xxx xxxxxxx",
      review: "<https://pip.pypa.io/en/stable/>",
    },
    {
      category: "Python",
      question: "What is a Python dictionary?",
      answer: "Key-value pairs",
      hint: "Maps keys to values.",
      blank: "xxx-xxxxx xxxxx",
      review: "<https://docs.python.org/3/tutorial/datastructures.html>",
    },
    {
      category: "Python",
      question: "What does PEP stand for?",
      answer: "Python Enhancement Proposal",
      hint: "Guides Python's development.",
      blank: "xxxxxx xxxxxxxxxxx xxxxxxxx",
      review: "<https://peps.python.org/>",
    },
    {
      category: "Python",
      question: "What does the `len()` function do?",
      answer: "Returns length",
      hint: "Counts elements in a sequence.",
      blank: "xxxxxxx xxxxxxx",
      review: "<https://docs.python.org/3/library/functions.html#len>",
    },
    {
      category: "Python",
      question: "What is a lambda function?",
      answer: "Anonymous function",
      hint: "Defined without a name.",
      blank: "xxxxxxxx xxxxxxxx",
      review: "<https://docs.python.org/3/tutorial/controlflow.html#lambda-expressions>",
    },
    {
      category: "Python",
      question: "How do you declare a variable in Python?",
      answer: "Assign a value",
      hint: "No type declaration required.",
      blank: "xxxxxx x xxxxx",
      review: "<https://docs.python.org/3/tutorial/introduction.html#numbers>",
    },
    {
      category: "Python",
      question: "What is the purpose of the `def` keyword?",
      answer: "Define a function",
      hint: "Used for creating reusable code.",
      blank: "xxxxxx x xxxxxxxx",
      review: "<https://docs.python.org/3/tutorial/controlflow.html#defining-functions>",
    },
    {
      category: "Python",
      question: "What is the output of `print(2 ** 3)`?",
      answer: "8",
      hint: "Exponentiation operator.",
      blank: "x",
      review: "<https://docs.python.org/3/reference/expressions.html#binary-arithmetic-operations>",
    },
    {
      category: "Python",
      question: "What is the difference between a list and a tuple?",
      answer: "Lists are mutable",
      hint: "Tuples cannot be changed.",
      blank: "xxxxx xxx xxxxxxx",
      review: "<https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences>",
    },
    {
      category: "Python",
      question: "What does the `import` statement do?",
      answer: "Includes modules",
      hint: "Loads external code.",
      blank: "xxxxxxx xxxxxxx",
      review: "<https://docs.python.org/3/reference/import.html>",
    },
    {
      category: "Python",
      question: "What is a virtual environment?",
      answer: "Isolated Python environment",
      hint: "Keeps dependencies separate.",
      blank: "xxxxxxxx xxxxxx xxxxxxxxx",
      review: "<https://docs.python.org/3/library/venv.html>",
    },
    {
      category: "Python",
      question: "What does the `range()` function return?",
      answer: "Sequence of numbers",
      hint: "Useful in loops.",
      blank: "xxxxxxxx xx xxxxxxx",
      review: "<https://docs.python.org/3/library/functions.html#func-range>",
    },
    {
      category: "Python",
      question: "What is the purpose of the `__init__` method?",
      answer: "Initialize objects",
      hint: "Constructor for classes.",
      blank: "xxxxxxxxxx xxxxxxx",
      review: "<https://docs.python.org/3/tutorial/classes.html#class-objects>",
    },
    {
      category: "Python",
      question: "What does the `try` keyword do?",
      answer: "Handles exceptions",
      hint: "Used with `except`.",
      blank: "xxxxxx xxxxxxxxxx",
      review: "<https://docs.python.org/3/tutorial/errors.html#handling-exceptions>",
    },
    {
      category: "Python",
      question: "What is the purpose of a decorator?",
      answer: "Modify functions",
      hint: "Uses `@` syntax.",
      blank: "xxxxxx xxxxxxxxx",
      review: "<https://docs.python.org/3/glossary.html#term-decorator>",
    },
    {
      category: "Python",
      question: "What does the `open()` function do?",
      answer: "Opens files",
      hint: "Used for file I/O.",
      blank: "xxxxx xxxxx",
      review: "<https://docs.python.org/3/library/functions.html#open>",
    },
    {
      category: "Python",
      question: "What is the difference between `is` and `==`?",
      answer: "`is` checks identity",
      hint: "Equality vs identity.",
      blank: "`xx` xxxxxx xxxxxxxx",
      review: "<https://realpython.com/python-is-identity-vs-equality/>",
    },
    {
      category: "Python",
      question: "What does `pass` do in Python?",
      answer: "No operation",
      hint: "Placeholder statement.",
      blank: "xx xxxxxxxxxx",
      review: "<https://docs.python.org/3/tutorial/controlflow.html#pass-statements>",
    },
    {
      category: "Python",
      question: "What is a Python module?",
      answer: "File with Python code",
      hint: "Used with `import`.",
      blank: "xxxx xxxx xxxxxx xxxx",
      review: "<https://docs.python.org/3/tutorial/modules.html>",
    },
    {
      category: "Python",
      question: "What is the purpose of `break` in a loop?",
      answer: "Exit loop early",
      hint: "Ends loop execution.",
      blank: "xxxx xxxx xxxxx",
      review: "<https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements>",
    },
    {
      category: "Python",
      question: "What does `None` represent in Python?",
      answer: "No value",
      hint: "Represents a null object.",
      blank: "xx xxxxx",
      review: "<https://docs.python.org/3/library/constants.html#None>",
    },
    {
      category: "Python",
      question: "What is the purpose of `assert`?",
      answer: "Debugging",
      hint: "Checks conditions.",
      blank: "xxxxxxxxx",
      review: "<https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement>",
    },
    {
      category: "Python",
      question: "What does the `type()` function return?",
      answer: "Object type",
      hint: "Checks data types.",
      blank: "xxxxxx xxxx",
      review: "<https://docs.python.org/3/library/functions.html#type>",
    },
    {
      category: "Python",
      question: "What is slicing in Python?",
      answer: "Subsets sequences",
      hint: "Uses `:` to define ranges.",
      blank: "xxxxxxx xxxxxxxxx",
      review: "<https://docs.python.org/3/tutorial/introduction.html#strings>",
    },
    {
      category: "Python",
      question: "What is a Python package?",
      answer: "Collection of modules",
      hint: "Includes `__init__.py`.",
      blank: "xxxxxxxxx xx xxxxxxx",
      review: "<https://docs.python.org/3/tutorial/modules.html#packages>",
    },
    {
      category: "Python",
      question: "What does the `dir()` function do?",
      answer: "Lists attributes",
      hint: "Introspection tool.",
      blank: "xxxxx xxxxxxxxxxx",
      review: "<https://docs.python.org/3/library/functions.html#dir>",
    },
    {
      category: "Python",
      question: "What is the Python Global Interpreter Lock (GIL)?",
      answer: "Thread safety mechanism",
      hint: "Limits concurrency.",
      blank: "xxxxxx xxxxx xxxxxxxxxx",
      review: "<https://realpython.com/python-gil/>",
    },
  ];
  
  module.exports = {
    category: "Python",
    fetchQuestion: async () => {
      const randomIndex = Math.floor(Math.random() * pythonquestions.length);
      return pythonquestions[randomIndex];
    },
    getAllQuestions: async () => {
      return pythonquestions;
    },
  };
  